version: '3'


services:

  pg_database:
    container_name: postgresql
    ports:
    - "5432:5432"
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d movies_database -U app"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/usr/share/postgres/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - .env
    networks:
      - my-network
  
  elasticsearch:
      image: elasticsearch:8.6.2
      container_name: elastic
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
      ports:
        - "9200:9200"
      healthcheck:
        test: ["CMD-SHELL", "curl -s http://localhost:9200/_cat/health?h=status | grep -q green"]
        interval: 10s
        timeout: 5s
        retries: 5
      volumes:
        - local:/elasticsearch/data
      networks:
        - my-network
    
  etl:
    build: app
    container_name: etl
    depends_on:
      pg_database:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    volumes:
        - etl-data:/usr/share/etl/data
    env_file:
      - .env
    networks:
      - my-network


volumes:
  local:
  
  postgres-data:
    driver: local
  etl-data:
    driver: local

networks:
  my-network:
    external: True 
